spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=H5+2Q9k2m7q9f7r0mY1Qqz8J4u1o9n3wWlP6yR2xA5s=

spring.data.redis.host=localhost
spring.data.redis.port=6379